"""
Django settings for magipy project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('MAGI_SECRET_KEY', 'MAGI_FOR_PRESIDENT!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('MAGIPY_ENV', 'development').lower() == 'development'

#if not DEBUG: raise ValueError('MAGIPY in production mode is not fully implemented.')
ALLOWED_HOSTS = []
if 'MAGIPY_SITE_URL' in os.environ:
    ALLOWED_HOSTS += os.environ.get('MAGIPY_SITE_URL', '').split(',')

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'social.apps.django_app.default',
    'annotations',
    'accounts',
    'magipy',
    'widget_tweaks'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'magipy.middleware.referralCatcher'
)

ROOT_URLCONF = 'magipy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, "templates"))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
               'django.contrib.auth.context_processors.auth',
               'django.core.context_processors.debug',
               'django.core.context_processors.i18n',
               'django.core.context_processors.media',
               'django.core.context_processors.static',
               'django.core.context_processors.tz',
               'django.contrib.messages.context_processors.messages',
               'social.apps.django_app.context_processors.backends',
               'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
   'social.backends.google.GoogleOAuth2',
   'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('MAGIPY_GOOGLE_CLIENT_ID')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('MAGIPY_GOOGLE_CLIENT_SECRET')
LOGIN_URL = '/account/login'
WSGI_APPLICATION = 'magipy.wsgi.application'
NODE_MAGI_URL = os.environ.get('NODE_MAGI_URL', 'http://localhost:8000')

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE'  : 'django.db.backends.postgresql_psycopg2',
        'NAME'    : os.environ.get('POSTGRES_DJANGO_DBNAME', 'magipy'),
        'USER'    : os.environ.get('POSTGRES_DJANGO_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_DJANGO_PASSWORD', ''),
        'HOST'    : os.environ.get('POSTGRES_DJANGO_HOST', ''),
        'PORT'    : os.environ.get('POSTGRES_DJANGO_PORT', '5432'),
        'client_encoding': 'UTF8',
        'default_transaction_isolation': 'read committed',
        'timezone': 'UTC'
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.environ.get('MAGI_STATIC_ROOT', '/var/www/magipy/static/')

if os.environ.get('MAGIPY_ENV', 'development').lower() == 'production':
    # Security for producttion environment - suggested by manage.py check --deploy
    # See https://docs.djangoproject.com/en/1.8/ref/settings/ for detailed info
    SECURE_CONTENT_TYPE_NOSNIFF=True
    SECURE_BROWSER_XSS_FILTER=True
    CSRF_COOKIE_HTTPONLY=True
    CSRF_COOKIE_SECURE=False
#    SESSION_COOKIE_SECURE=True
    X_FRAME_OPTIONS='DENY'

    # If we want MAGI to be https only, we have to set this as well as the header,
    # and also change NGINX settings:
    # See https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-SECURE_PROXY_SSL_HEADER
    #SECURE_SSL_REDIRECT=True
    #SECURE_PROXY_SSL_HEADER="HTTP_"
